on: 
  push:
    paths:
      - 'firmware/**/*'
      - '!firmware/**/*.md'
  pull_request:
    paths:
      - 'firmware/**/*'
      - '!firmware/**/*.md'
jobs:
  compile_lint:
    strategy:
      matrix:
        sketch_dir:
          - "firmware/erratic_TS25"
          - "firmware/lutum"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Compile sketch ${{matrix.sketch_dir}}
        run: arduino-cli compile
        working-directory: ${{matrix.sketch_dir}}
      - name: Lint sketch ${{matrix.sketch_dir}}
        uses: arduino/arduino-lint-action@v2        
        with:
          path: ${{matrix.sketch_dir}}

